/**
  ******************************************************************************************************************
  * @file    ImageBMP.c 
  * @author  Colin DEMOUGE & Thibaut LEFRANCOIS
  * @version v1.0
  * @date    2023
  * @modification	
  * @brief   
  ******************************************************************************************************************/
	
#include "GLCD_Config.h"
#include "ImagesBMP.h"

const unsigned short bmpPacManClose[HEIGHT_PACMAN*WIDTH_PACMAN]={

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpPacManOpenRight[HEIGHT_PACMAN*WIDTH_PACMAN]={

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpPacManOpenLeft[HEIGHT_PACMAN*WIDTH_PACMAN]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpPacManOpenDown[HEIGHT_PACMAN*WIDTH_PACMAN]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpPacManOpenUp[HEIGHT_PACMAN*WIDTH_PACMAN]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,

GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpEnnemiClose[HEIGHT_ENNEMI*WIDTH_ENNEMI]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};





const unsigned short bmpEnnemiOpenRight[HEIGHT_ENNEMI*WIDTH_ENNEMI]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpEnnemiOpenLeft[HEIGHT_ENNEMI*WIDTH_ENNEMI]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpEnnemiOpenDown[HEIGHT_ENNEMI*WIDTH_ENNEMI]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpEnnemiOpenUp[HEIGHT_ENNEMI*WIDTH_ENNEMI]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,GLCD_COLOR_RED   ,

GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_RED   ,GLCD_COLOR_BLACK ,

GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,

};



const unsigned short bmpFood[HEIGHT_FOOD*WIDTH_FOOD]=

{

GLCD_COLOR_BLACK ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_BLACK,

GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE,

GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE,

GLCD_COLOR_BLACK ,GLCD_COLOR_WHITE ,GLCD_COLOR_WHITE ,GLCD_COLOR_BLACK,

};
